# -*- coding: utf-8 -*-
"""Replication Package.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APYAiw_-IutaYunANjiIkeTR0BarUmsk

##Required Libraries
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import sys
import matplotlib.pyplot as plt
from scipy.stats import norm, skew, kurtosis, jarque_bera
from statsmodels.tsa.stattools import adfuller
import re
from joblib import Parallel, delayed
from IPython.display import display
import warnings
warnings.filterwarnings("ignore")

"""## in-Sample Exercises"""

archivo_excel = "/content/df.xlsx"

# Cargar el archivo Excel en un DataFrame de pandas
df = pd.read_excel(archivo_excel)

# 1. Eliminar filas con al menos un NaN (excepto 'Date' si existe)
df_clean = df.drop(columns=['Date'], errors='ignore').dropna()

# 2. Función para formatear Jarque–Bera con asteriscos de significancia
def format_jb(series):
    jb_stat, jb_p = jarque_bera(series)
    if jb_p < 0.01:
        return f"{jb_stat:.2f}***"
    elif jb_p < 0.05:
        return f"{jb_stat:.2f}**"
    elif jb_p < 0.1:
        return f"{jb_stat:.2f}*"
    else:
        return f"{jb_stat:.2f}"

# 3. Función para obtener todas las estadísticas
def get_stats(series):
    s = series.dropna()
    mean = s.mean()
    min_ = s.min()
    max_ = s.max()
    std = s.std()
    skewness = skew(s)
    excess_kurtosis = kurtosis(s, fisher=True)
    jb_stat = format_jb(s)
    adf_stat = adfuller(s, regression='ct', autolag='AIC')[0]
    return pd.Series([
        mean, min_, max_, std, skewness, excess_kurtosis,
        jb_stat, adf_stat
    ])

# 4. Aplicar a cada columna
result = df_clean.apply(get_stats).T

# 5. Asignar nombres de columnas
result.columns = [
    'Mean', 'Min.', 'Max.', 'Std. Dev.', 'Skew.', 'Ex. Kurt.',
    'Jarque–Bera', 'ADF statistics'
]

# 6. Redondear las columnas numéricas (excepto JB que ya está formateado como string)
for col in ['Mean', 'Min.', 'Max.', 'Std. Dev.', 'Skew.', 'Ex. Kurt.', 'ADF statistics']:
    result[col] = pd.to_numeric(result[col], errors='coerce').round(5)

result

# Guardar en Excel si lo deseas
result.to_excel("descriptivos_Technicals.xlsx", index=False)

"""##Resultados In-Sample"""

"""
Replicable pipeline for running OLS + Newey–West (HAC) models of the form:
    y_f? = const + y? + x_i
across all x-columns in a DataFrame, one at a time.

Outputs:
- full_results: all coefficients (const, AR term, and x) for every model
- tables: per-dependent compact table with only the evaluated x (x, coef, tstat, r2)
- Writes a single Excel file 'In_Sample.xlsx' with two sheets; falls back to CSVs if needed.
"""


# =========================
# 1) Data preparation
# =========================
# Expect a DataFrame `df` already in memory with at least these columns:
# Dependents: y_f, y_f7, y_f14, y_f28
# AR terms : y, y7, y14, y28
# Predictors: x* (e.g., x1, x2, ..., or any column starting with 'x')
#
# If needed, load your data here (uncomment and adjust the path):
# df = pd.read_csv("your_file.csv")

# =========================
# 2) Model specification
# =========================
dependents = ['y_f', 'y_f7', 'y_f14', 'y_f28']
ar_terms   = ['y',   'y7',   'y14',   'y28']   # must align 1-to-1 with dependents

# Discover x-columns. Option A: any column starting with 'x'
x_cols = [c for c in df.columns if isinstance(c, str) and c.startswith('x')]

# Option B (stricter): only x followed by digits (x1, x2, ...)
# x_cols = [c for c in df.columns if re.fullmatch(r'x\d+', str(c))]

# =========================
# 3) Estimation loop
# =========================
results_rows = []

for dep, ar in zip(dependents, ar_terms):
    if dep not in df.columns or ar not in df.columns:
        continue

    for x in x_cols:
        if x in {dep, ar}:
            continue

        needed = [dep, ar, x]
        if not all(col in df.columns for col in needed):
            continue

        df_tmp = df[needed].dropna()
        if df_tmp.empty:
            continue

        Y = df_tmp[dep]
        X = sm.add_constant(df_tmp[[ar, x]])  # add intercept

        model = sm.OLS(Y, X).fit(cov_type='HAC', cov_kwds={'maxlags': 1})

        for var in ['const', ar, x]:
            results_rows.append({
                'dependent': dep,
                'ar_term': ar,
                'x': x,
                'model': f'{dep} ~ {ar} + {x}',
                'variable': var,
                'coef': model.params.get(var, np.nan),
                'stderr': model.bse.get(var, np.nan),
                'tstat': model.tvalues.get(var, np.nan),
                'pvalue': model.pvalues.get(var, np.nan),
                'r2': model.rsquared,
                'nobs': int(model.nobs)
            })

# =========================
# 4) Build output tables
# =========================
full_results = pd.DataFrame(results_rows)

compact_blocks = []
for dep in dependents:
    if dep not in full_results['dependent'].unique():
        continue

    block = full_results[
        (full_results['dependent'] == dep) &
        (full_results['variable'] == full_results['x'])
    ][['dependent', 'x', 'coef', 'tstat', 'r2']].copy()

    block['x'] = pd.Categorical(block['x'], categories=x_cols, ordered=True)
    block = block.sort_values('x')
    compact_blocks.append(block)

tables = (pd.concat(compact_blocks, ignore_index=True)
          if compact_blocks
          else pd.DataFrame(columns=['dependent', 'x', 'coef', 'tstat', 'r2']))

# =========================
# 5) Console display
# =========================
print("\n================= FULL RESULTS (first 10 rows) =================")
if not full_results.empty:
    print(full_results.head(10).to_string(index=False))
else:
    print("No models were estimated. Check column names and missing data.")

print("\n================= COMPACT TABLES BY DEPENDENT (x order preserved) =================")
for dep in dependents:
    block = tables[tables['dependent'] == dep]
    if block.empty:
        continue
    print(f"\n--- {dep} ---")
    print(block[['x', 'coef', 'tstat', 'r2']].to_string(index=False))

# =========================
# 6) Write outputs to disk
# =========================
try:
    with pd.ExcelWriter("In_Sample.xlsx") as writer:
        full_results.to_excel(writer, sheet_name="full_results", index=False)
        tables.to_excel(writer, sheet_name="tables", index=False)
    print("\nWrote 'In_Sample.xlsx' with sheets: full_results, tables.")
except Exception as e:
    print(f"\nWarning: Excel write failed ({e}). Falling back to CSV.")
    full_results.to_csv("In_Sample_full_results.csv", index=False)
    tables.to_csv("In_Sample_tables.csv", index=False)
    print("Wrote 'In_Sample_full_results.csv' and 'In_Sample_tables.csv'.")

"""##Out-of-sample Exercises"""

archivo_excel = "/content/df_oos.xlsx"

# Cargar el archivo Excel en un DataFrame de pandas
df = pd.read_excel(archivo_excel)

# ------------ Quick config (adjust as needed) ------------
START_RATIO = 0.5          # use 0.3 if you have few rows
MIN_OBS     = 10           # minimum observations to train/score
HAC_LAGS    = 1            # maxlags for HAC (Clark–West)
MAX_VARS_PREVIEW = 12      # how many 'x' names to show in the initial diagnostic

# Candidate dependent variables (filtered to those that actually exist in df)
DEPENDENTS_CANDIDATES = ['y_f', 'y_f7', 'y_f14', 'y_f28']


# ------------ Utilities ------------
def stars_one_sided(t: float) -> str:
    """
    Return significance stars for a one-sided Z test based on t-stat.
    Thresholds (upper tail):
      - '***' if t >= 2.3263 (1%)
      - '**'  if t >= 1.6449 (5%)
      - '*'   if t >= 1.2816 (10%)
    """
    if t >= 2.3263: return '***'  # 1%
    if t >= 1.6449: return '**'   # 5%
    if t >= 1.2816: return '*'    # 10%
    return ''


def info(msg: str) -> None:
    """Print a message and flush stdout for real-time logs (e.g., in Colab)."""
    print(msg)
    sys.stdout.flush()


def clark_west_y_r2_para_x(
    df: pd.DataFrame,
    x_var: str,
    dep_col: str = 'y_f',
    start_ratio: float = START_RATIO,
    min_obs: int = MIN_OBS,
    hac_lags: int = HAC_LAGS
):
    """
    Compute Clark & West (one-sided) and OOS R² for a single predictor `x_var`
    against a target column `dep_col` using an expanding window.

    Models:
      Core   : dep_col ~ const + x_var
      Bench  : dep_col ~ const    (historical mean)

    Steps:
      1) Keep only the necessary columns and clean Inf/NaN.
      2) Determine the first out-of-sample index from `start_ratio` (respecting `min_obs`).
      3) For each expanding step:
         - Estimate OLS on Core and Bench with all data up to j-1.
         - Predict at j for both models.
      4) After the loop, compute:
         - MSE(core) and MSE(bench)
         - OOS R² := 1 - MSE(core) / MSE(bench)
         - Clark–West t-stat via HAC( maxlags = hac_lags )
      5) Return a result dict and simple diagnostics (n valid, n OOS).

    Returns
    -------
    (result_dict, error_msg, n_valid, n_oos)
      - result_dict: {'dependent','Variable','OOS_R2','CW_t'} or None on error
      - error_msg  : str with a short reason if skipped, otherwise None
      - n_valid    : number of valid rows after cleaning
      - n_oos      : number of out-of-sample forecasts produced
    """
    # Keep minimal columns and clean
    sub = df[[x_var, dep_col]].copy()
    sub.replace([np.inf, -np.inf], np.nan, inplace=True)
    sub.dropna(inplace=True)

    n = len(sub)
    if n < min_obs + 1:
        return None, "Too few valid rows after cleaning", None, None

    start_idx = max(int(n * start_ratio), min_obs)
    if start_idx >= n:
        return None, f"start_index={start_idx} >= n={n}", None, None

    sub['Pronostico_core'] = np.nan
    sub['Pronostico_benchmark'] = np.nan

    # Expanding window
    for j in range(start_idx, n):
        train = sub.iloc[:j]
        if len(train) < min_obs:
            continue

        X = sm.add_constant(train[[x_var]], has_constant='add')
        y = train[dep_col]
        try:
            core = sm.OLS(y, X).fit()
        except Exception as e:
            return None, f"OLS core failed at j={j}: {e}", None, None

        xj = sub.iloc[j][x_var]
        if pd.isna(xj):
            continue

        sub.iat[j, sub.columns.get_loc('Pronostico_core')] = float(
            core.predict(pd.DataFrame({'const': [1.0], x_var: [xj]}))
        )

        # Benchmark: historical mean (intercept-only OLS)
        try:
            bench = sm.OLS(y, np.ones((len(y), 1))).fit()
            sub.iat[j, sub.columns.get_loc('Pronostico_benchmark')] = float(
                bench.predict(np.array([[1.0]]))
            )
        except Exception as e:
            return None, f"OLS benchmark failed at j={j}: {e}", None, None

    dd = sub.dropna(subset=['Pronostico_core', 'Pronostico_benchmark'])
    if len(dd) < min_obs:
        return None, f"Fewer than {min_obs} OOS forecasts (n={len(dd)})", None, None

    e1 = dd[dep_col] - dd['Pronostico_benchmark']
    e2 = dd[dep_col] - dd['Pronostico_core']
    mse_bench = float(np.mean(e1**2))
    mse_core  = float(np.mean(e2**2))
    if mse_bench == 0.0:
        return None, "Benchmark MSE = 0 (perfect constant), cannot compute OOS R²", None, None

    r2_oos = 1.0 - (mse_core / mse_bench)

    cw_term = e1 * (e1 - e2)
    Xc = np.ones((len(cw_term), 1))
    try:
        cw_fit = sm.OLS(cw_term.values, Xc).fit(cov_type='HAC', cov_kwds={'maxlags': hac_lags})
        cw_t = float(cw_fit.tvalues[0])
    except Exception as e:
        return None, f"Clark–West failed: {e}", None, None

    return {'dependent': dep_col, 'Variable': x_var, 'OOS_R2': r2_oos, 'CW_t': cw_t}, None, n, len(dd)


# ------------ MAIN EXECUTION ------------
print("=== Initial diagnostic ==="); sys.stdout.flush()

# 1) df must exist
if 'df' not in globals():
    info("[ERROR] DataFrame 'df' not found in the current environment. Load your data into a variable named df and re-run this cell.")
else:
    # 2) Structure and columns
    info(f"[INFO] df.shape = {df.shape}")
    try:
        info(f"[INFO] First columns: {list(df.columns)[:12]}")
    except Exception:
        pass

    # 3) Available dependents
    dependents = [d for d in DEPENDENTS_CANDIDATES if d in df.columns]
    if not dependents:
        info("[ERROR] None of the expected target columns found: y_f, y_f7, y_f14, y_f28.")
    else:
        info(f"[INFO] Dependents to evaluate: {dependents}")

        # 4) Select x-variables (by name prefix) and keep numeric only
        x_cols = [c for c in df.columns if str(c).startswith('x')]
        if not x_cols:
            info("[ERROR] No columns detected that start with 'x'. If your predictors use other names, define a list explicitly and adapt the code.")
        else:
            x_cols = [c for c in x_cols if pd.api.types.is_numeric_dtype(df[c])]
            if not x_cols:
                info("[ERROR] Columns starting with 'x' are not numeric. Convert to numeric or check names.")
            else:
                info(f"[INFO] Detected x-variables (up to {MAX_VARS_PREVIEW}): "
                     f"{x_cols[:MAX_VARS_PREVIEW]}{' ...' if len(x_cols) > MAX_VARS_PREVIEW else ''}")

                # 5) Quick NaN/Inf counts after cleaning
                _chk = df[dependents + x_cols].replace([np.inf, -np.inf], np.nan)
                nan_counts = _chk.isna().sum().sort_values(ascending=False).head(8)
                info(f"[INFO] Top columns with NaN after replacing Inf (sample):\n{nan_counts}")

                # 6) Run evaluation for each dependent and each x
                resultados = []
                skipped = []  # list of tuples (dependent, variable) for skipped cases
                for dep_col in dependents:
                    info(f"\n[MODEL] Evaluating dependent: {dep_col}")
                    for v in x_cols:
                        info(f"[RUN] {dep_col} ~ const + {v} ...")
                        res, err, n_valid, n_oos = clark_west_y_r2_para_x(df, v, dep_col=dep_col)
                        if err is not None:
                            info(f"[SKIP] {dep_col} / {v}: {err}")
                            skipped.append((dep_col, v))
                            continue
                        res['stars'] = stars_one_sided(res['CW_t'])
                        res['OOS_R2_fmt'] = f"{res['OOS_R2']:.3f}{res['stars']}"
                        resultados.append(res)
                        info(f"[OK]   {dep_col} / {v}: OOS_R2={res['OOS_R2']:.4f}  "
                             f"CW_t={res['CW_t']:.3f}  {res['stars']}  (n_valid={n_valid}, n_oos={n_oos})")

                # 7) Final output or empty-diagnostic
                print("\n=== Results ==="); sys.stdout.flush()
                if resultados:
                    out = pd.DataFrame(resultados)[['dependent', 'Variable', 'OOS_R2', 'CW_t', 'OOS_R2_fmt']]

                    # Preserve original order of dependents and variables
                    dep_order = {d: i for i, d in enumerate(dependents)}
                    var_order = {c: i for i, c in enumerate(x_cols)}
                    out = (
                        out.sort_values(
                            by=['dependent', 'Variable'],
                            key=lambda s: s.map(dep_order) if s.name == 'dependent' else s.map(var_order)
                        ).reset_index(drop=True)
                    )

                    # Print head and keep full table in session
                    print(out.head(20).to_string(index=False)); sys.stdout.flush()
                    resultados_cw = out
                    info("\n[INFO] Full results are stored in the variable 'resultados_cw'.")

                    # 8) Write to disk (Excel with two sheets) and optional download
                    try:
                        # Build skipped DataFrame (if any)
                        if skipped:
                            skipped_df = pd.DataFrame(skipped, columns=['dependent', 'Variable'])
                        else:
                            skipped_df = pd.DataFrame(columns=['dependent', 'Variable'])

                        xlsx_path = "In_Sample.xlsx"  # updated filename per your preference
                        with pd.ExcelWriter(xlsx_path) as writer:
                            out.to_excel(writer, sheet_name="tables", index=False)
                            skipped_df.to_excel(writer, sheet_name="skipped", index=False)
                        print(f"\nWrote '{xlsx_path}' with sheets: tables, skipped.")
                    except Exception as e:
                        # Fallback to CSVs if Excel writing fails
                        print(f"\nWarning: Excel write failed ({e}). Falling back to CSV.")
                        out.to_csv("In_Sample_tables.csv", index=False)
                        if skipped:
                            pd.DataFrame(skipped, columns=['dependent', 'Variable']).to_csv("In_Sample_skipped.csv", index=False)
                        else:
                            pd.DataFrame(columns=['dependent', 'Variable']).to_csv("In_Sample_skipped.csv", index=False)
                        print("Wrote 'In_Sample_tables.csv' and 'In_Sample_skipped.csv'.")

                    # 9) Optional Colab download: comment out if not needed
                    try:
                        from google.colab import files
                        files.download(xlsx_path)
                    except Exception:
                        pass

                else:
                    info("[WARN] No results produced for any variable or dependent.")
                    info("Typical causes: too many NaN values, high START_RATIO, too few rows for OOS, benchmark MSE = 0.")
                    info(f"Suggestions: lower START_RATIO (e.g., 0.3), reduce MIN_OBS (e.g., 5), "
                         f"check that series are not constant and predictors are numeric.")

"""## Trading Strategy: Anatoliev and Gerko

"""

# -------------------- Quick config (adjust as needed) --------------------

EXCEL_PATH = "/content/df_oos_trading.xlsx"  # input file path
START_RATIO = 0.7                             # expanding-window start as share of rows
TRADING_DAYS_PER_YEAR = 365                   # used for annualization

# -------------------- Utilities --------------------

def info(msg: str) -> None:
    """Print a message and flush stdout for real-time logs (e.g., in Colab)."""
    print(msg)
    sys.stdout.flush()

# -------------------- DATA LOAD --------------------

info("[INFO] Loading data...")
df = pd.read_excel(EXCEL_PATH)
info(f"[INFO] df.shape = {df.shape}")

# Basic existence checks
if 'y_f' not in df.columns:
    raise ValueError("[ERROR] Target column 'y_f' not found in the DataFrame.")

# Detect automatically all columns starting with 'x' (predictors)
variables_core = [col for col in df.columns if str(col).startswith("x")]
if not variables_core:
    raise ValueError("[ERROR] No predictors detected with prefix 'x'.")

# Keep only numeric predictors
variables_core = [c for c in variables_core if pd.api.types.is_numeric_dtype(df[c])]
if not variables_core:
    raise ValueError("[ERROR] Predictors with prefix 'x' are not numeric after inspection.")

# Replace Inf with NaN for safety; we won't drop rows globally, only when needed
df = df.replace([np.inf, -np.inf], np.nan)

start_index = max(int(len(df) * START_RATIO), 1)
if start_index >= len(df):
    raise ValueError(f"[ERROR] start_index={start_index} >= n={len(df)}; reduce START_RATIO or add more rows.")

info(f"[INFO] Using expanding-window start at index {start_index} (≈ {START_RATIO:.0%} of data)")

# -------------------- BENCHMARK (intercept-only model) --------------------

info("[STEP] Computing benchmark expanding forecasts...")
df['const_benchmark_coef'] = np.nan
df['Pronostico_benchmark'] = np.nan

for i in range(start_index, len(df)):
    df_train = df.iloc[:i].dropna(subset=['y_f'])  # ensure target is not NaN
    if len(df_train) < 2:
        continue
    y_target = df_train['y_f']
    X_bench = np.ones((len(df_train), 1))
    model_bench = sm.OLS(y_target, X_bench).fit()
    df.at[df.index[i], 'const_benchmark_coef'] = model_bench.params[0]
    df.at[df.index[i], 'Pronostico_benchmark'] = model_bench.params[0]

# Directional accuracy and "strategy" series for the benchmark
df['acierto_direccion_benchmark'] = np.nan
mask_bmk = df.index >= df.index[start_index]
df.loc[mask_bmk, 'acierto_direccion_benchmark'] = np.where(
    np.sign(df.loc[mask_bmk, 'y_f']) == np.sign(df.loc[mask_bmk, 'Pronostico_benchmark']), 1, 0
)

df['estrategia_benchmark'] = np.nan
df.loc[mask_bmk, 'estrategia_benchmark'] = np.where(
    df.loc[mask_bmk, 'acierto_direccion_benchmark'] == 1,
    np.abs(df.loc[mask_bmk, 'y_f']),
    -1 * np.abs(df.loc[mask_bmk, 'y_f'])
)

# -------------------- CORE LOOP (intercept + single predictor) --------------------

info("[STEP] Computing core expanding forecasts for each predictor x...")
for var in variables_core:
    df[f'const_coef_{var}'] = np.nan
    df[f'{var}_coef'] = np.nan
    df[f'Pronostico_core_{var}'] = np.nan
    df[f'acierto_direccion_core_{var}'] = np.nan
    df[f'estrategia_core_{var}'] = np.nan

    for i in range(start_index, len(df)):
        # ensure both y_f and the predictor are present in the training slice
        df_train = df.iloc[:i].dropna(subset=['y_f', var])
        if len(df_train) < 2:
            continue

        y_target = df_train['y_f']
        X_core = sm.add_constant(df_train[[var]], has_constant='add')
        model_core = sm.OLS(y_target, X_core).fit()

        # store fitted coefficients at time i
        df.at[df.index[i], f'const_coef_{var}'] = model_core.params['const']
        df.at[df.index[i], f'{var}_coef'] = model_core.params[var]

        # one-step-ahead forecast at time i (only if predictor is not NaN at i)
        x_i = df.at[df.index[i], var]
        if pd.notna(x_i):
            pronostico = model_core.params['const'] + model_core.params[var] * x_i
            df.at[df.index[i], f'Pronostico_core_{var}'] = pronostico

    # directional accuracy and "strategy" series for this predictor
    mask_core = df.index >= df.index[start_index]
    df.loc[mask_core, f'acierto_direccion_core_{var}'] = np.where(
        np.sign(df.loc[mask_core, 'y_f']) == np.sign(df.loc[mask_core, f'Pronostico_core_{var}']),
        1, 0
    )

    df.loc[mask_core, f'estrategia_core_{var}'] = np.where(
        df.loc[mask_core, f'acierto_direccion_core_{var}'] == 1,
        np.abs(df.loc[mask_core, 'y_f']),
        -1 * np.abs(df.loc[mask_core, 'y_f'])
    )

# -------------------- STRATEGIES DATAFRAME --------------------

info("[STEP] Building strategies DataFrame...")
estrategias_cols = [f'estrategia_core_{var}' for var in variables_core] + ['estrategia_benchmark']
df_estrategias = df[estrategias_cols].dropna(how='all').copy()  # keep rows where at least one strategy is present

# -------------------- SEP STATISTIC (one-sided, right tail) --------------------

info("[STEP] Computing SEP statistics (one-sided, H0: mean <= 0 vs H1: mean > 0)...")
sep_results = []

for col in df_estrategias.columns:
    series = df_estrategias[col].dropna()
    P = len(series)

    if P > 1:
        mean_r = float(series.mean())
        std_r = float(series.std(ddof=1))
        sep_stat = (np.sqrt(P) * mean_r) / std_r if std_r > 0 else np.nan
        p_value = 1 - norm.cdf(sep_stat) if not np.isnan(sep_stat) else np.nan  # one-sided (right tail)

        mean_r_annual = mean_r * TRADING_DAYS_PER_YEAR
        sharpe_annual = (mean_r / std_r) * np.sqrt(TRADING_DAYS_PER_YEAR) if std_r > 0 else np.nan
    else:
        mean_r = np.nan
        std_r = np.nan
        sep_stat = np.nan
        p_value = np.nan
        mean_r_annual = np.nan
        sharpe_annual = np.nan

    sep_results.append({
        'Estrategia': col,
        'SEP_stat': sep_stat,
        'p_value_one_sided': p_value,
        'mean': mean_r,
        'std': std_r,
        'mean_annual': mean_r_annual,
        'sharpe_annual': sharpe_annual,
        'N': P
    })

# Results DataFrame
df_resultados_sep = pd.DataFrame(sep_results)
print("\n=== SEP Results (head) ===")
print(df_resultados_sep.head().to_string(index=False))

# -------------------- Optional export --------------------

try:
    out_xlsx = "In_Sample_SEP.xlsx"
    with pd.ExcelWriter(out_xlsx) as writer:
        df_resultados_sep.to_excel(writer, sheet_name="sep_results", index=False)
        df_estrategias.to_excel(writer, sheet_name="strategies_timeseries", index=False)
    info(f"\n[INFO] Wrote '{out_xlsx}' with sheets: sep_results, strategies_timeseries.")
except Exception as e:
    info(f"\n[WARN] Excel export failed ({e}). Falling back to CSV.")
    df_resultados_sep.to_csv("In_Sample_SEP_results.csv", index=False)
    df_estrategias.to_csv("In_Sample_SEP_strategies.csv", index=False)
    info("[INFO] Wrote 'In_Sample_SEP_results.csv' and 'In_Sample_SEP_strategies.csv'.")

# Optional Colab download
try:
    from google.colab import files
    files.download(out_xlsx)
except Exception:
    pass

"""## Trading Strategy: Wang et al.(2020)"""

archivo_excel = "/content/df_oos_trading.xlsx"

# Cargar el archivo Excel en un DataFrame de pandas
df = pd.read_excel(archivo_excel)

# ---------------------------------------------------------------------
# UTILITIES
# ---------------------------------------------------------------------
def natural_key_x(name: str):
    """
    Natural sorting key for variables starting with 'x'.
    - Ensures x1 < x2 < ... < x10 (instead of x1, x10, x2).
    If there is no number, send it to the end.
    """
    m = re.match(r'^x(\d+)$', name)
    if m:
        return (0, int(m.group(1)))
    # If it's x_<suffix> with letters or different format, try to extract first number
    m2 = re.match(r'^x(\d+)', name)
    if m2:
        return (1, int(m2.group(1)), name)
    return (2, name)

def detectar_variables_x(df: pd.DataFrame):
    """
    Return the list of columns that start with 'x', sorted naturally.
    """
    xs = [c for c in df.columns if isinstance(c, str) and c.startswith('x')]
    xs = sorted(xs, key=natural_key_x)
    return xs

# ---------------------------------------------------------------------
# MAIN FUNCTIONS
# ---------------------------------------------------------------------
def procesar_variable_estrategia(df_original, x_var, start_ratio, gamma=6, tau=0.001):
    """
    df_original: in-memory DataFrame that already contains 'y_f', 'Treasury', and x-variables.
    x_var: predictor name (e.g., 'x1', 'x2', …) or 'Benchmark_global'.
    start_ratio: fraction (0-1) to define the start index for the expanding window.
    gamma: risk aversion coefficient (default 6).
    tau: transaction cost per change in weight (default 0.001).
    """
    df = df_original.copy()

    # Force numeric types (avoid strings -> NaNs)
    cols_num = []
    for base in ['y_f', 'Treasury']:
        if base in df.columns:
            cols_num.append(base)
    cols_num += [c for c in df.columns if isinstance(c, str) and c.startswith('x')]
    for c in cols_num:
        df[c] = pd.to_numeric(df[c], errors='coerce')

    # Init columns
    for col in ['Pronostico_core', 'volatility_28d', 'peso_optimo', 'retorno_portafolio']:
        df[col] = np.nan

    # 28-day rolling variance of y_f
    df['volatility_28d'] = df['y_f'].rolling(window=28).var()

    # Start index
    start_index = int(len(df) * start_ratio)

    # Main expanding loop
    for j in range(start_index, len(df)):
        df_window = df.iloc[:j].copy()

        if x_var == "Benchmark_global":
            # Benchmark: constant-only (similar to RW ~ 0 if y_f is a return)
            df_train = df_window[['y_f']].dropna()
            if len(df_train) < 10:
                continue
            X = np.ones((len(df_train), 1))
            y = df_train['y_f']
            model = sm.OLS(y, X).fit()
            pronostico = model.predict(np.array([[1]])).item()
        else:
            # Core with x_var
            if x_var not in df.columns:
                continue  # skip if variable does not exist in df
            df_train = df_window[[x_var, 'y_f']].replace([np.inf, -np.inf], np.nan).dropna()
            if len(df_train) < 10:
                continue
            X_core = sm.add_constant(df_train[[x_var]])
            y_target = df_train['y_f']
            model = sm.OLS(y_target, X_core).fit()

            x_j = df.at[df.index[j], x_var]
            if pd.isna(x_j):
                continue
            pronostico = model.predict(np.array([[1, x_j]])).item()

        df.at[df.index[j], 'Pronostico_core'] = pronostico

        expected_return = pronostico
        expected_vol = df.at[df.index[j], 'volatility_28d']
        realized_return = df.at[df.index[j], 'y_f']
        treasury_return = df.at[df.index[j], 'Treasury']

        # Mean-variance style optimal weight (bounded [0, 1.5])
        if pd.notna(expected_return) and pd.notna(expected_vol) and expected_vol > 0:
            w_star = (1 / gamma) * (expected_return / expected_vol)
            w_star = max(0, min(1.5, w_star))
            df.at[df.index[j], 'peso_optimo'] = w_star

            # Portfolio return with transaction cost
            if j > 0 and pd.notna(df.at[df.index[j - 1], 'peso_optimo']):
                w_prev = df.at[df.index[j - 1], 'peso_optimo']
                tcost = tau * abs(w_star - w_prev)

                if pd.notna(realized_return) and pd.notna(treasury_return):
                    port_ret = (
                        w_star * realized_return
                        + (1 - w_star) * treasury_return
                        - tcost
                    )
                    df.at[df.index[j], 'retorno_portafolio'] = port_ret

    # Metrics
    serie = df['retorno_portafolio'].dropna()
    P = len(serie)
    if P > 1:
        mean_r = serie.mean()
        std_r = serie.std(ddof=1)
        sep_stat = (np.sqrt(P) * mean_r) / std_r if std_r > 0 else np.nan
        p_value = 1 - norm.cdf(sep_stat) if not np.isnan(sep_stat) else np.nan
        mean_ann = mean_r * 365
        sharpe_ann = (mean_r / std_r) * np.sqrt(365) if std_r > 0 else np.nan
    else:
        mean_r = std_r = sep_stat = p_value = mean_ann = sharpe_ann = np.nan

    resumen = pd.DataFrame({
        'Estrategia': [x_var],
        'SEP_stat': [sep_stat],
        'p_value': [p_value],
        'media_diaria': [mean_r],
        'std_diaria': [std_r],
        'media_anual': [mean_ann],
        'sharpe_anual': [sharpe_ann]
    })

    pesos = df[['peso_optimo']].copy()
    pesos['peso_BTC'] = pesos['peso_optimo']
    pesos['peso_Treasury'] = 1 - pesos['peso_BTC']
    pesos['Estrategia'] = x_var
    pesos = pesos.dropna()

    return resumen, pesos


def evaluar_todas_estrategias(
    df_original,
    variables,
    start_ratio,
    path_resultados="/content/resultados_todos.xlsx",
    path_pesos="/content/pesos_todos.xlsx",
    n_jobs=-1
):
    """
    variables: list of predictor names (e.g., ['x1', 'x2', ...]) present in df.
    path_resultados: Excel file path (metrics) in /content for Colab.
    path_pesos: if not None, also saves portfolio weights by strategy.
    n_jobs: number of processes for joblib (-1 = use all cores).
    """
    if not variables:
        raise ValueError("No variables starting with 'x' were found in the DataFrame.")

    variables_full = list(variables) + ['Benchmark_global']

    # Run in parallel
    resultados = Parallel(n_jobs=n_jobs, backend='loky')(
        delayed(procesar_variable_estrategia)(df_original, var, start_ratio)
        for var in variables_full
    )

    df_metricas = pd.concat([r[0] for r in resultados], ignore_index=True)
    df_pesos = pd.concat([r[1] for r in resultados], ignore_index=True)

    # Save results
    if path_resultados:
        df_metricas.to_excel(path_resultados, index=False)
    if path_pesos:
        df_pesos.to_excel(path_pesos, index=False)

    # Quick on-screen preview
    print("\n=== FIRST WEIGHTS BY STRATEGY ===")
    for nombre in df_pesos['Estrategia'].unique():
        print(f"\nStrategy: {nombre}")
        display(df_pesos[df_pesos['Estrategia'] == nombre].head())

    return df_metricas, df_pesos

# ---------------------------------------------------------------------
# EXECUTION (Colab)
# ---------------------------------------------------------------------
# Make sure you already have 'df' in memory. It must include: 'y_f', 'Treasury', and predictors 'x...'.

# 1) Automatically detect all 'x*'
variables = detectar_variables_x(df)

print(f"Detected {len(variables)} explanatory variables.")
if len(variables) > 0:
    print("First 15:", variables[:15])

# 2) Run evaluation
df_metricas, df_pesos = evaluar_todas_estrategias(
    df_original=df,
    variables=variables,
    start_ratio=0.7,  # adjust initial split if desired
    path_resultados="/content/resultados_todos.xlsx",
    path_pesos="/content/pesos_todos.xlsx",
    n_jobs=-1
)

print("\nOutput paths in Colab:")
print("Metrics:", "/content/resultados_todos.xlsx")
print("Weights:", "/content/pesos_todos.xlsx")

# ---------------------------------------------------------------------
# (Optional) Save to Drive:
# from google.colab import drive
# drive.mount('/content/drive')
# df_metricas.to_excel("/content/drive/MyDrive/resultados_todos.xlsx", index=False)
# df_pesos.to_excel("/content/drive/MyDrive/pesos_todos.xlsx", index=False)

